Repository RE6CT/jeju-olleyo, pull requests merged in 2025-04, with the labels that each got.

#4 Chore/#1 project setting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs_improvement.md
  .github/ISSUE_TEMPLATE/etc.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  LICENSE
  README.md
  eslint.config.mjs
  next.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/fonts/.gitkeep
  public/images/.gitkeep
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/commons/.gitkeep
  src/components/layouts/.gitkeep
  src/components/ui/.gitkeep
  src/config/.gitkeep
  src/constants/.gitkeep
  src/lib/apis/.gitkeep
  src/lib/hooks/.gitkeep
  src/lib/mutations/.gitkeep
  src/lib/queries/.gitkeep
  src/lib/supabase/client.ts
  src/lib/supabase/middleware.ts
  src/lib/supabase/server.ts
  src/lib/utils/.gitkeep
  src/types/common.type.ts
  src/zustand/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: chore

#6 Chore/#5 project setting 2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs_improvement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/middleware.ts
  src/components/features/.gitkeep
  src/config/tq-provider.tsx
  src/lib/supabase/client.ts
  src/lib/supabase/middleware.ts
  src/lib/supabase/server.ts
Labels: chore

#16 add: label, input ui 공통 컴포넌트 구현 (#13)
  components.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/components/ui/.gitkeep
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: feat

#17 Feat/#8 header
  components.json
  package.json
  pnpm-lock.yaml
  src/components/features/place-modal.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/search-bar.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  supabase/.temp/cli-latest
Labels: feat

#20 Feat/#12 kakao map init
  package.json
  src/app/maptest/page.tsx
  src/components/features/map/kakao-map.tsx
  src/types/global/window.type.ts
  src/types/kakao-map.type.ts
Labels: feat

#19 Feat/#9 button
  package.json
  pnpm-lock.yaml
  src/components/features/like-button.tsx
  src/components/ui/button.tsx
  src/lib/apis/add-like.api.ts
  src/lib/apis/count-like.api.ts
  src/lib/apis/delete-like.api.ts
  src/lib/apis/get-like.api.ts
  src/lib/hooks/use-like.ts
  src/lib/supabase/server.ts
  src/types/supabase.type.ts
  supabase/.gitignore
  supabase/config.toml
Labels: feat

#22 Feat/#14 make comment
  package.json
  pnpm-lock.yaml
  src/app/plan-detail/_components/comment-input.tsx
  src/app/plan-detail/_components/comment.tsx
  src/app/plan-detail/_components/comments-section.tsx
  src/types/plan-detail.type.ts
Labels: feat

#23 Feat/#18 auth page UI
  package.json
  pnpm-lock.yaml
  public/images/google.svg
  public/images/kakaotalk.svg
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/ui/card.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/separator.tsx
Labels: feat

#28 Feat/#18 auth page UI
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/features/auth/auth-footer.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-header.tsx
  src/components/features/auth/auth-layout.tsx
  src/components/features/auth/auth-password-input.tsx
  src/components/features/auth/auth-social-login.tsx
  src/components/features/auth/auth-social-provider.tsx
  src/types/auth.type.ts
Labels: feat, style

#30 Feat/#12 marker basic
  src/app/maptest/page.tsx
  src/components/features/map/kakao-map.tsx
  src/components/features/map/marker.tsx
  src/types/kakao-map.type.ts
Labels: feat

#31 Feat/#26 apply react hook form
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/features/auth/auth-footer.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-header.tsx
  src/components/features/auth/auth-layout.tsx
  src/components/features/auth/auth-password-input.tsx
  src/components/features/auth/auth-social-login.tsx
  src/components/features/auth/auth-social-provider.tsx
  src/types/auth.type.ts
Labels: feat

#29 Feat/#10 re modal 장소 모달창
  src/components/features/place-modal.tsx
Labels: feat

#34 Feat/#12 marker clustering
  src/app/maptest/page.tsx
  src/components/features/map/clusterer.tsx
  src/components/features/map/kakao-map.tsx
  src/types/kakao-map.type.ts
Labels: feat

#35 Feat/#27 mypage modal
  src/app/layout.tsx
  src/app/mypage/_components/sidebar.tsx
  src/app/mypage/bookmarks/page.tsx
  src/app/mypage/comments/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/likes/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/app/mypage/reservation/page.tsx
  src/components/layouts/.gitkeep
  src/components/layouts/Header.tsx
  src/components/layouts/header.tsx
  src/components/layouts/mypage-modal.tsx
Labels: feat

#38 Feat/#12 route basic
  src/app/maptest/page.tsx
  src/components/features/map/clusterer.tsx
  src/components/features/map/kakao-map.tsx
  src/components/features/map/polyline.tsx
  src/types/kakao-map.type.ts
Labels: feat

#45 Feat/#44 Type Camelize
  src/lib/utils/.gitkeep
  src/lib/utils/camelize.ts
  src/types/common.type.ts
Labels: feat

#36 Feat/#27 mypage modal
  public/images/.gitkeep
  public/images/default-profile.png
  src/app/mypage/_components/sidebar.tsx
  src/app/mypage/reservation/page.tsx
  src/app/mypage/reservations/page.tsx
  src/components/commons/.gitkeep
  src/components/commons/profile-image.tsx
  src/components/features/.gitkeep
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/components/layouts/mypage-modal.tsx
  src/lib/hooks/.gitkeep
  src/lib/hooks/use-click-outside.ts
  src/lib/utils/get-image-with-fallback.ts
  src/types/common.type.ts
  src/types/mypage.type.ts
Labels: feat

#32 Feat/#9 bookmark
  src/components/features/bookmark.tsx
  src/lib/apis/.gitkeep
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/delete-bookmark.api.ts
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/hooks/use-bookmark.ts
Labels: feat

#41 Feat/#26 apply auth zod
  src/app/(auth)/sign-up/page.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-header.tsx
  src/components/ui/card.tsx
  src/constants/auth.constants.ts
  src/lib/schemas/auth-schema.ts
  src/types/auth.type.ts
Labels: feat

#46 Style/#12 map UI docs
  src/app/error.tsx
  src/app/maptest/page.tsx
  src/components/features/map/README.md
  src/components/features/map/kakao-map.tsx
  src/types/kakao-map.type.ts
Labels: docs, style

#50 Feat/#43 auth supabase
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/page.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/constants/auth.constants.ts
  src/lib/apis/add-like.api.ts
  src/lib/apis/auth-server.api.ts
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/delete-bookmark.api.ts
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/apis/count-like.api.ts
  src/lib/apis/delete-like.api.ts
  src/lib/apis/get-like.api.ts
  src/lib/schemas/auth-schema.ts
  src/lib/supabase/client.ts
  src/lib/supabase/middleware.ts
  src/lib/supabase/server.ts
  src/types/auth.type.ts
Labels: feat

#54 Feat/#39 bookmarks page
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/images/default-image.png
  src/app/layout.tsx
  src/app/mypage/_components/sidebar.tsx
  src/app/mypage/bookmarks/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/commons/place-image.tsx
  src/components/features/bookmark.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/hooks/use-bookmark.ts
  src/lib/utils/get-image-with-fallback.ts
  src/types/common.type.ts
  src/types/mypage.type.ts
  src/types/supabase.type.ts
Labels: feat

#57 Feat/#48 schedule list
  package.json
  pnpm-lock.yaml
  src/app/my-plan/page.tsx
  src/components/features/plan/plan-card.tsx
  src/components/ui/dropdown-menu.tsx
  src/types/plan.type.ts
Labels: feat

#52 Feat/#43 auth supabase
  next.config.mjs
  src/app/(auth)/forgot-password/layout.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/auth/callback/route.ts
  src/app/layout.tsx
  src/app/middleware.ts
  src/app/mypage/bookmarks/page.tsx
  src/app/page.tsx
  src/components/features/auth/auth-client-info.tsx
  src/components/features/auth/auth-error-message.tsx
  src/components/features/auth/auth-layout.tsx
  src/components/features/auth/auth-social-login.tsx
  src/components/features/auth/auth-social-provider.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/components/ui/alert.tsx
  src/components/ui/button.tsx
  src/config/.gitkeep
  src/config/auth-provider.tsx
  src/constants/.gitkeep
  src/constants/auth.constants.ts
  src/lib/apis/auth-browser.api.ts
  src/lib/apis/auth-server.api.ts
  src/lib/hooks/use-auth.ts
  src/lib/schemas/auth-schema.ts
  src/lib/supabase/middleware.ts
  src/lib/supabase/server.ts
  src/lib/utils/auth-error.util.ts
  src/middleware.ts
  src/types/auth.type.ts
  src/zustand/auth.store.ts
Labels: feat

#60 feat: 사용자 제공자 표시 로직 개선 및 불필요한 로그 제거
  src/components/features/nav-mypage/mypage-modal.tsx
  src/lib/apis/auth-browser.api.ts
Labels: feat

#58 Feat/#48 schedule header
  package.json
  pnpm-lock.yaml
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/components/layouts/header.tsx
  src/components/ui/popover.tsx
Labels: style, refactor

#61 Feat/#55 social login
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/api/set-provider/route.ts
  src/app/auth/callback/route.ts
  src/app/layout.tsx
  src/components/features/auth/auth-error-message.tsx
  src/components/features/auth/auth-footer.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-header.tsx
  src/components/features/auth/auth-password-input.tsx
  src/components/features/auth/auth-social-login.tsx
  src/components/features/auth/auth-social-provider.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/ui/card.tsx
  src/config/auth-provider.tsx
  src/lib/apis/auth-browser.api.ts
  src/lib/apis/auth-server.api.ts
  src/lib/hooks/use-auth.ts
  src/types/auth.type.ts
  src/zustand/.gitkeep
Labels: feat

#64 Feat/#48 schedule data
  src/app/my-plan/_components/plan-filter-input.tsx
  src/app/my-plan/_components/plan-filter-menu.tsx
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/components/features/plan/my-plan-card.tsx
  src/constants/plan.constants.ts
  src/lib/apis/plan/plan.api.ts
  src/types/plan.type.ts
Labels: feat

#63 Feat/#37 profile page
  src/app/mypage/_components/sidebar.tsx
  src/app/mypage/account/_components/account-personal-info.tsx
  src/app/mypage/account/_components/account-profile-image-button.tsx
  src/app/mypage/account/_components/account-profile-info.tsx
  src/app/mypage/account/_components/account-security-info.tsx
  src/app/mypage/account/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile/page.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/types/mypage.type.ts
Labels: feat

#69 Feat/#33 search page 검색 페이지
  package.json
  pnpm-lock.yaml
  src/app/search/_components/banner.tsx
  src/app/search/page.tsx
  src/components/layouts/header.tsx
  src/components/layouts/search-bar.tsx
  src/constants/path.constants.ts
  src/lib/apis/search/get-place.api.ts
  src/lib/hooks/use-search.ts
  src/lib/supabase/client.ts
  src/types/search.type.ts
Labels: feat

#74 Feat/#42 likes page
  src/app/(mypage)/likes/page.tsx
  src/app/my-plan/page.tsx
  src/components/features/plan/plan-card.tsx
  src/constants/plan.constants.ts
  src/lib/apis/like/get-like.api.ts
  src/lib/apis/plan/plan.api.ts
  src/types/plan.type.ts
  src/types/supabase.type.ts
Labels: feat

#72 Feat/#37 profile page
  src/app/(mypage)/account/_components/account-personal-info.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-security-info.tsx
  src/app/(mypage)/account/page.tsx
  src/components/ui/input.tsx
  src/constants/mypage.constants.ts
Labels: refactor

#70 Feat/#62 main page category
  public/images/google_mypage.png
  public/images/kakaotalk_mypage.png
  public/images/mail_mypage.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/commons/profile-image.tsx
  src/components/features/home/category-tap.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/constants/header.constants.ts
  src/constants/home.constants.ts
  src/lib/hooks/use-auth.ts
  src/lib/hooks/use-category-navigation.ts
  src/types/home.categoty.type.ts
  src/zustand/home.category.store.ts
Labels: feat, refactor

#73 Style/#48 schedule UI
  src/app/globals.css
  src/app/my-plan/_components/plan-filter-menu.tsx
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/page.tsx
  src/components/ui/error-message.tsx
  src/components/ui/pagination.tsx
  src/constants/path.constants.ts
  src/constants/plan.constants.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/queries/use-delete-plan.ts
  src/lib/queries/use-get-filtered-plans.ts
  src/lib/utils/date.ts
  src/types/plan.type.ts
Labels: feat, style, refactor

#75 Refactor/#65 auth refactor
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/api/set-provider/route.ts
  src/app/auth/callback/route.ts
  src/components/features/auth/auth-client-info.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-password-input.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/config/auth-provider.tsx
  src/constants/auth.constants.ts
  src/constants/path.constants.ts
  src/lib/apis/auth/auth-browser.api.ts
  src/lib/apis/auth/auth-server.api.ts
  src/lib/hooks/use-auth-check.ts
  src/lib/hooks/use-auth.ts
  src/lib/hooks/use-redirect-params.ts
  src/lib/hooks/use-remember-email.ts
  src/lib/hooks/use-social-login.ts
  src/lib/schemas/auth-schema.ts
  src/lib/supabase/middleware.ts
  src/lib/utils/auth-error.util.ts
  src/lib/utils/auth-refresh.util.ts
  src/lib/utils/auth-session.util.ts
  src/middleware.ts
  src/types/auth.type.ts
  src/zustand/auth.store.ts
Labels: refactor

#87 Update .coderabbit.yaml
  .coderabbit.yaml
Labels: chore

#83 Refactor/#65 auth refactor
  src/app/(auth)/forgot-password/layout.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/features/auth/auth-form-error-message.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-social-login.tsx
  src/constants/auth.constants.ts
  src/lib/schemas/auth-schema.ts
  src/types/auth.type.ts
Labels: feat, refactor

#89 Refactor/#65 auth refactor
  src/app/(auth)/sign-in/page.tsx
  src/app/api/set-provider/route.ts
  src/components/features/auth/auth-client-info.tsx
  src/components/features/home/category-tap.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/config/auth-provider.tsx
  src/constants/path.constants.ts
  src/lib/apis/auth/auth-browser.api.ts
  src/lib/apis/auth/auth-server.api.ts
  src/lib/hooks/use-auth.ts
  src/lib/hooks/use-forgot-password.ts
  src/lib/hooks/use-reset-password.ts
  src/lib/hooks/use-social-login.ts
  src/lib/utils/auth-error.util.ts
  src/lib/utils/handleError.ts
  src/middleware.ts
  src/types/auth.type.ts
Labels: feat, refactor

#93 chore: 폰트 정의 (#91)
  src/app/globals.css
  tailwind.config.ts
Labels: chore

#95 Style/#91 font definitions
  src/app/globals.css
  tailwind.config.ts
Labels: style

#96 fix: 파일 경로 수정
  src/app/api/korea-tour/detail/route.ts
  src/app/test/placemodaltest/page.tsx
  src/types/korea-tour.type.ts
  src/types/place-modal.type.ts
Labels: hotfix

#90 Feat/#37 profile page
  src/app/(mypage)/account/_components/account-personal-info.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-security-info.tsx
  src/app/(mypage)/account/page.tsx
  src/constants/mypage.constants.ts
  src/constants/supabase.constant.ts
  src/lib/apis/profile/update-profile.api.ts
  src/lib/hooks/use-get-provider.ts
  src/lib/schemas/auth-schema.ts
  src/types/supabase.type.ts
Labels: feat

#97 Feat/#62 main page carousel
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/icons/accommodation.svg
  public/icons/mypage-comment.svg
  public/icons/mypage-location.svg
  public/icons/mypage-schedule.svg
  src/app/page.tsx
  src/components/features/auth/auth-error-message.tsx
  src/components/features/auth/auth-footer.tsx
  src/components/features/auth/auth-layout.tsx
  src/components/features/home/category-tap.tsx
  src/components/features/home/home-category-tap.tsx
  src/components/features/home/home-main-carousel-container.tsx
  src/components/features/home/home-main-carousel.tsx
  src/components/features/home/home-navigation-button.tsx
  src/components/features/home/home-progress.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/components/layouts/search-bar.tsx
  src/components/ui/carousel.tsx
  src/components/ui/command.tsx
  src/constants/auth.constants.ts
  src/constants/home.constants.ts
  src/lib/apis/home/home.api.ts
  src/lib/hooks/use-carousel-progress.ts
  src/lib/hooks/use-category-navigation.ts
  src/types/home.carousel.type.ts
  src/types/home.category.type.ts
  src/types/supabase.type.ts
  src/zustand/home.category.store.ts
  supabase/.temp/cli-latest
Labels: feat

#101 feat: 사용자 프로필 이미지 처리 개선 및 기본값 수정 (#65)
  src/lib/apis/auth/auth-browser.api.ts
  src/lib/apis/auth/auth-server.api.ts
Labels: feat

#102 Feat/#37 profile page
  public/icons/add.svg
  public/icons/cancel.svg
  public/icons/close.svg
  public/icons/plus.svg
  public/images/default_place_image.png
  public/images/default_place_image.svg
  public/images/default_plan_image.png
  public/images/default_plan_image.svg
  public/images/default_profile.png
  public/images/default_profile.svg
  src/app/(mypage)/_components/mypage-sidebar.tsx
  src/app/(mypage)/_components/sidebar.tsx
  src/app/(mypage)/account/_components/account-profile-image-button.tsx
  src/app/(mypage)/account/_components/account-profile-image.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-profile-modal.tsx
  src/app/(mypage)/account/page.tsx
  src/app/(mypage)/layout.tsx
  src/app/globals.css
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/ui/modal.tsx
  src/constants/mypage.constants.ts
  src/constants/path.constants.ts
  src/lib/apis/auth/auth-server.api.ts
  src/lib/apis/profile/update-profile.api.ts
  src/lib/utils/get-image-with-fallback.ts
  src/types/mypage.type.ts
  tailwind.config.ts
Labels: feat

#104 Feat/#62 main page weather
  public/weather/clear.jpg
  public/weather/cloudy.jpg
  public/weather/partly-cloudy-day.jpg
  public/weather/rain.jpg
  public/weather/snow.jpg
  public/weather/thunderstorm.jpg
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/api/weather/route.ts
  src/app/error.tsx
  src/app/loading.tsx
  src/app/page.tsx
  src/app/plan-detail/_components/place-card.tsx
  src/app/plan-detail/new/_components/plan-form.tsx
  src/app/plan-detail/new/_components/plan-header.tsx
  src/app/plan-detail/new/_components/plan-map.tsx
  src/app/plan-detail/new/_components/plan-schedule.tsx
  src/components/commons/duration.tsx
  src/components/features/auth/auth-error-message.tsx
  src/components/features/auth/auth-footer.tsx
  src/components/features/auth/auth-form-error-message.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-header.tsx
  src/components/features/home/home-category-tap.tsx
  src/components/features/home/home-main-carousel-container.tsx
  src/components/features/home/home-main-carousel.tsx
  src/components/features/home/home-navigation-button.tsx
  src/components/features/home/home-progress.tsx
  src/components/features/home/home-weather-card.tsx
  src/components/features/home/home-weather-container.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/components/layouts/search-bar.tsx
  src/lib/apis/home/home.api.ts
  src/lib/apis/home/home.weather.api.ts
  src/lib/hooks/use-category-navigation.ts
  src/lib/utils/home-weather-image.ts
  src/lib/utils/home-weather-messages.ts
  src/types/home.weather.type.ts
Labels: feat

#106 Refactor/auth error message
  src/components/features/auth/auth-layout.tsx
  src/lib/apis/auth/auth-browser.api.ts
  src/lib/apis/auth/auth-server.api.ts
Labels: feat, refactor

#105 chore: 좋아요, 북마크 컴포넌트화 작업 진행 (#88)
  src/components/commons/bookmark-icon.tsx
  src/components/commons/like-icon.tsx
Labels: feat, style

#107 Feat/#103 comments page
  public/images/email_mypage.png
  public/images/kakao_mypage.png
  src/app/(mypage)/_components/mypage-sidebar.tsx
  src/app/(mypage)/account/page.tsx
  src/app/(mypage)/bookmarks/page.tsx
  src/app/(mypage)/comments/_components/my-comment.tsx
  src/app/(mypage)/comments/page.tsx
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/likes/page.tsx
  src/app/(mypage)/reservations/page.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/header.tsx
  src/components/layouts/nav.tsx
  src/constants/header.constants.ts
  src/lib/apis/comments/get-comments.api.ts
  src/lib/apis/profile/get-profile-data-count.ts
  src/lib/queries/.gitkeep
  src/lib/queries/use-get-data-count.ts
  src/types/comment.type.ts
  src/types/mypage.type.ts
  src/types/supabase.type.ts
Labels: feat

#108 Feat/#37 profile page
  src/app/(mypage)/account/_components/account-personal-info.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-profile-modal.tsx
  src/app/(mypage)/account/page.tsx
  src/constants/mypage.constants.ts
  src/lib/apis/profile/update-profile.api.ts
  src/lib/schemas/auth-schema.ts
Labels: feat

#109 Feat/#37 profile page
  src/app/(mypage)/account/_components/account-personal-info.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-security-info.tsx
  src/app/(mypage)/account/page.tsx
  src/components/features/auth/auth-password-input.tsx
  src/constants/mypage.constants.ts
  src/lib/apis/profile/update-profile.api.ts
  src/lib/schemas/auth-schema.ts
  src/lib/schemas/change-password-schema.ts
  src/types/auth.type.ts
Labels: feat

#111 Feat/#100 category
  src/app/categories/[category]/category-client.tsx
  src/app/categories/[category]/layout.tsx
  src/app/categories/[category]/page.tsx
  src/app/not-found.tsx
  src/config/tq-provider.tsx
  src/constants/home.constants.ts
  src/constants/path.constants.ts
  src/lib/apis/search/get-place-by-categories.api.ts
  src/lib/apis/search/get-place.api.ts
  src/lib/queries/use-get-places.ts
  src/lib/queries/use-prefetch-places.ts
  src/middleware.ts
Labels: feat

#49 Feat/#7 card
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/commons/combo-box.tsx
  src/components/features/card/category-card.tsx
  src/components/features/card/plan-card.tsx
  src/components/features/card/search-card.tsx
  src/constants/path.constants.ts
  src/middleware.ts
  src/types/card.type.ts
  src/types/common.type.ts
Labels: feat

#114 Feat/#110 community page
  public/images/jeju-banner.png
  src/app/(mypage)/layout.tsx
  src/app/community/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/features/banner/jeju-banner.tsx
  src/components/layouts/nav.tsx
  src/constants/auth.constants.ts
  src/constants/path.constants.ts
  src/lib/apis/plan/plan.api.ts
  src/middleware.ts
  src/types/common.type.ts
  src/types/supabase.type.ts
  tailwind.config.ts
Labels: feat

#118 Feat/#88 plan new search bookmark
  src/app/my-plan/_components/plan-filter-input.tsx
  src/app/my-plan/_components/plan-filter-menu.tsx
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/app/plan-detail/_components/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/place-card-category.tsx
  src/app/plan-detail/_components/place-card.tsx
  src/app/plan-detail/_components/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/place-sidemenu.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/_components/plan-header.tsx
  src/app/plan-detail/_components/plan-map.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/app/plan-detail/_components/search-sidemenu.tsx
  src/app/plan-detail/_components/sidemenu-place-card.tsx
  src/app/plan-detail/new/_components/.gitkeep
  src/app/plan-detail/new/page.tsx
  src/components/commons/bookmark-icon.tsx
  src/components/commons/category-filter-tabs.tsx
  src/components/commons/duration.tsx
  src/components/commons/like-icon.tsx
  src/components/ui/dynamic-pagination.tsx
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/hooks/use-bookmark-query.ts
  src/types/plan-detail.type.ts
  src/types/supabase.type.ts
Labels: feat

#122 Feat/#110 community page
  src/app/community/_components/community-plan-list.tsx
  src/app/community/_components/community-sort-dropdown.tsx
  src/app/community/page.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/features/home/home-popular-schedules.tsx
  src/lib/apis/plan/plan.api.ts
  src/types/community.type.ts
  src/types/plan.type.ts
  src/types/supabase.type.ts
Labels: feat

#120 feat: 인기 장소 섹션 추가 및 드래그 기능 구현 (#62)
  src/app/(mypage)/bookmarks/page.tsx
  src/app/categories/[category]/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/components/commons/place-image.tsx
  src/components/features/card/place-card.tsx
  src/components/features/home/home-category-tap.tsx
  src/components/features/home/home-popular-places.tsx
  src/components/features/home/home-popular-schedules.tsx
  src/constants/home.constants.ts
  src/lib/apis/home/home.popular.api.ts
  src/lib/hooks/use-drag-scroll.ts
  src/lib/hooks/use-popular-places.ts
  src/lib/mutations/.gitkeep
  src/lib/mutations/use-bookmark-mutation.ts
  src/types/card.type.ts
  src/types/home.popular-place.type.ts
  src/types/supabase.type.ts
  src/zustand/bookmark.store.ts
  src/zustand/home.place.store.ts
Labels: feat

#127 style: 메인페이지 이미지 변경 및 불필요한 카테고리 타입 및 상수 제거 (#125)
  public/banner-images/plan-banner.svg
  public/weather/clear.svg
  public/weather/cloudy.svg
  public/weather/partly-cloudy-day.svg
  public/weather/rain.svg
  public/weather/snow.svg
  public/weather/thunderstorm.svg
  public/weather/wind.svg
  src/components/features/home/home-category-tap.tsx
  src/components/features/home/home-popular-places.tsx
  src/constants/home.constants.ts
  src/types/home.popular-place.type.ts
Labels: style, refactor

#126 Feat/#112 search 검색 및 카테고리 페이지
  public/emptyresult/empty_result.svg
  public/line-banner-images/farm_ad.png
  public/line-banner-images/resort_ad.png
  src/app/categories/[category]/category-client.tsx
  src/app/categories/[category]/page.tsx
  src/app/loading.tsx
  src/app/search/_components/banner.tsx
  src/app/search/_components/empty-result.tsx
  src/app/search/page.tsx
  src/components/layouts/search-bar.tsx
  src/lib/hooks/use-search.ts
  src/types/card.type.ts
  tailwind.config.ts
Labels: feat

#128 Feat/#124 like button
  src/app/(mypage)/bookmarks/_components/bookmarks-list.tsx
  src/app/(mypage)/bookmarks/page.tsx
  src/app/my-plan/_components/plan-filter-section.tsx
  src/components/commons/like-icon.tsx
  src/components/features/card/place-card.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/features/like-button.tsx
  src/lib/apis/like/add-like.api.ts
  src/lib/apis/like/delete-like.api.ts
  src/lib/apis/like/get-like.api.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-like.ts
  src/lib/mutations/use-bookmark-mutation.ts
  src/lib/mutations/use-like-mutation.ts
  src/types/plan.type.ts
  src/types/supabase.type.ts
Labels: feat

#132 Feat/#88 plan new data
  package.json
  pnpm-lock.yaml
  src/app/plan-detail/_components/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/place-card-category.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/_components/plan-header.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/app/plan-detail/_components/schedule-save-modal.tsx
  src/app/plan-detail/_components/search-sidemenu.tsx
  src/app/test/maptest/page.tsx
  src/components/commons/character-modal.tsx
  src/config/tq-provider.tsx
  src/lib/apis/plan/plan.api.ts
  src/types/supabase.type.ts
Labels: feat

#135 Style/#130 auth page style change
  public/images/google-logo.svg
  public/images/google.svg
  public/images/kakao-logo.svg
  public/images/kakaotalk.svg
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/features/auth/auth-error-message.tsx
  src/components/features/auth/auth-form-error-message.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-header.tsx
  src/components/features/auth/auth-layout.tsx
  src/components/features/auth/auth-social-login.tsx
  src/components/features/home/home-popular-places.tsx
  src/components/layouts/footer.tsx
  src/components/ui/card.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/lib/hooks/use-reset-password.ts
Labels: style

#136 Style/#125 main page css change
  src/app/page.tsx
  src/components/features/banner/jeju-banner.tsx
  src/components/features/card/place-card.tsx
  src/components/features/home/home-category-tap.tsx
  src/components/features/home/home-main-carousel.tsx
  src/components/features/home/home-popular-places.tsx
  src/components/features/home/home-popular-schedules.tsx
  src/constants/home.constants.ts
  src/lib/hooks/use-category-navigation.ts
  src/types/home.category.type.ts
  src/zustand/home.category.store.ts
Labels: feat, style, refactor

#138 Feat/#137 password change modal
  src/app/(auth)/reset-password/page.tsx
  src/components/commons/reset-password-success-modal.tsx
  src/components/ui/no-close-button-dialog.tsx
  src/types/auth.type.ts
Labels: feat, refactor

#142 style: 푸터 컴포넌트 레이아웃 및 스타일 개선 (#141)
  src/components/layouts/footer.tsx
Labels: style

#144 Refactor/#115 main page refactor
  src/components/features/card/plan-vertical-card.tsx
  src/components/features/home/home-category-tap.tsx
  src/components/features/home/home-popular-schedules.tsx
  src/components/features/home/home-weather-card.tsx
  src/components/features/home/home-weather-header.tsx
Labels: style

#146 Feat/#134 category infinite scroll
  package.json
  pnpm-lock.yaml
  src/app/categories/[category]/category-client.tsx
  src/app/categories/[category]/layout.tsx
  src/app/categories/[category]/page.tsx
  src/app/plan-detail/_components/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/place-card-category.tsx
  src/app/plan-detail/_components/place-card.tsx
  src/app/plan-detail/_components/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/place-sidemenu.tsx
  src/app/plan-detail/_components/search-sidemenu.tsx
  src/app/plan-detail/_components/sidemenu-place-card.tsx
  src/app/search/_components/banner.tsx
  src/app/search/page.tsx
  src/components/commons/category-badge.tsx
  src/components/commons/category-filter-tabs.tsx
  src/components/commons/like-icon.tsx
  src/components/commons/place-image.tsx
  src/components/features/card/place-card.tsx
  src/components/features/like-button.tsx
  src/components/features/plan/place-modal.tsx
  src/constants/home.constants.ts
  src/lib/apis/category/get-place.ts
  src/lib/apis/home/home.popular.api.ts
  src/lib/apis/search/get-place-by-categories.api.ts
  src/lib/hooks/use-bookmark-query.ts
  src/lib/mutations/use-bookmark-mutation.ts
  src/lib/queries/use-get-places.ts
  src/lib/queries/use-prefetch-places.ts
  src/types/category.type.ts
  src/types/plan-detail.type.ts
Labels: feat

#143 Feat/#129 place detail page 장소 상세 페이지 수정
  public/character/happy.png
  src/app/loading.tsx
  src/app/places/[id]/_components/place-location.tsx
  src/app/places/[id]/_components/plan-including-place.tsx
  src/app/places/[id]/page.tsx
  src/app/plan-detail/_components/search-sidemenu.tsx
  src/app/search/page.tsx
  src/components/commons/bookmark-icon.tsx
  src/constants/path.constants.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/apis/search/get-place.api.ts
  src/lib/hooks/use-bookmark-query.ts
  src/middleware.ts
  src/types/search.type.ts
  src/types/supabase.type.ts
Labels: feat

#147 Feat/alert modal
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(mypage)/account/_components/account-security-info.tsx
  src/app/layout.tsx
  src/components/commons/alert-modal.tsx
  src/components/features/auth/auth-form.tsx
  src/components/features/auth/auth-password-input.tsx
  src/components/features/banner/jeju-banner.tsx
  src/lib/hooks/use-alert.ts
  src/types/alert.type.ts
  src/types/auth.type.ts
  src/zustand/alert.store.ts
Labels: feat

#145 Feat/#88 plan new map
  public/map/mapmarker-day1.png
  public/map/mapmarker-day10.png
  public/map/mapmarker-day11.png
  public/map/mapmarker-day12.png
  public/map/mapmarker-day13.png
  public/map/mapmarker-day14.png
  public/map/mapmarker-day15.png
  public/map/mapmarker-day2.png
  public/map/mapmarker-day3.png
  public/map/mapmarker-day4.png
  public/map/mapmarker-day5.png
  public/map/mapmarker-day6.png
  public/map/mapmarker-day7.png
  public/map/mapmarker-day8.png
  public/map/mapmarker-day9.png
  public/map/primary500-mapmarker.png
  public/map/secondary300-mapmarker.png
  src/app/plan-detail/_components/place-card-category.tsx
  src/app/plan-detail/_components/place-card.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/_components/plan-header.tsx
  src/app/plan-detail/_components/plan-map.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/app/plan-detail/_components/search-sidemenu.tsx
  src/components/features/map/clusterer.tsx
  src/components/features/map/kakao-map.tsx
  src/components/features/map/marker.tsx
  src/constants/map.constants.ts
  src/constants/plan.constants.ts
  src/lib/apis/map/directions.ts
  src/lib/utils/map.util.ts
  src/types/kakao-map.type.ts
Labels: feat

#149 Refactor/#115 main page refactor
  src/app/globals.css
Labels: refactor

#153 Feat/#40 air ticket
  package.json
  pnpm-lock.yaml
  src/app/air-ticket/_components/date-options.tsx
  src/app/air-ticket/_components/ticket-card.tsx
  src/app/air-ticket/_components/ticket-list.tsx
  src/app/air-ticket/_components/ticket-search-form.tsx
  src/app/air-ticket/_utils/ticket-uitls.ts
  src/app/air-ticket/page.tsx
  src/app/api/flight/route.js
  src/components/commons/combo-box.tsx
  src/components/features/air-ticket-searchbar.tsx
  src/constants/ticket.constants.ts
  src/types/air-ticket-type.ts
Labels: feat, refactor

#154 Feat/#152 plan detail layout
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/place-card.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/_components/plan-header.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/app/plan-detail/not-found.tsx
  src/lib/apis/plan/plan.api.ts
  src/types/plan.type.ts
Labels: feat

#158 fix: 비로그인 상태의 사용자도 일정 상세 페이지에 접근 가능하도록 수정 (#152)
  src/app/plan-detail/[planId]/page.tsx
Labels: hotfix

#159 Fix/middleware update
  src/components/layouts/nav.tsx
  src/constants/auth.constants.ts
Labels: feat, refactor

#161 Hotfix/#152 plan detail route
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/plan-detail/_components/day-select-required-modal.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/lib/queries/use-delete-plan.ts
Labels: hotfix

#166 Refatctor/#164 plan code cleanup
  src/app/my-plan/_components/plan-filter-input.tsx
  src/app/my-plan/_components/plan-filter-menu.tsx
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/app/places/[id]/page.tsx
  src/app/plan-detail/_components/plan-schedule.tsx
  src/components/features/map/polyline.tsx
  src/components/features/plan/place-modal.tsx
  src/constants/map.constants.ts
  src/lib/apis/map/directions.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/utils/map.util.ts
  src/types/global/window.type.ts
  src/types/kakao-map.type.ts
  src/types/place.type.ts
  src/types/plan-detail.type.ts
  src/types/plan.type.ts
  src/types/supabase.type.ts
Labels: refactor

#168 Refactor/prefetch hook convention
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/categories/[category]/page.tsx
  src/lib/queries/use-get-places.ts
Labels: bugfix

#165 Refactor/type kpr 강푸른 만든 페이지 내 타입 any 제거
  src/app/api/korea-tour/detail/route.ts
  src/app/places/[id]/_components/place-location.tsx
  src/constants/tour.constants.ts
  tsconfig.json
Labels: refactor

#174 refactor: 에러 처리 방식을 개선하고 타입을 명확히 함 (#172)
  src/lib/apis/auth/auth-browser.api.ts
  src/lib/apis/auth/auth-server.api.ts
  src/lib/apis/home/home.popular.api.ts
  src/lib/hooks/use-auth.ts
  src/lib/hooks/use-social-login.ts
  src/lib/utils/handleError.ts
  src/types/home.weather.type.ts
Labels: refactor

#175 Refactor/#164 plan detail component hook
  src/app/(mypage)/account/_components/account-profile-modal.tsx
  src/app/(mypage)/bookmarks/_components/bookmarks-list.tsx
  src/app/categories/[category]/category-client.tsx
  src/app/places/[id]/page.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/core/plan-header.tsx
  src/app/plan-detail/_components/core/plan-map.tsx
  src/app/plan-detail/_components/core/plan-schedule.tsx
  src/app/plan-detail/_components/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/features/card/place-card.tsx
  src/app/plan-detail/_components/features/card/places-renderer.tsx
  src/app/plan-detail/_components/features/comment/comment-input.tsx
  src/app/plan-detail/_components/features/comment/comment.tsx
  src/app/plan-detail/_components/features/comment/comments-section.tsx
  src/app/plan-detail/_components/features/modal/day-select-required-modal.tsx
  src/app/plan-detail/_components/features/modal/schedule-created-modal.tsx
  src/app/plan-detail/_components/features/modal/schedule-delete-modal.tsx
  src/app/plan-detail/_components/features/modal/schedule-save-modal.tsx
  src/app/plan-detail/_components/features/notfound/not-found.tsx
  src/app/plan-detail/_components/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/features/sidemenu/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/_components/plan-header.tsx
  src/app/plan-detail/_components/sidemenu-place-card.tsx
  src/app/search/page.tsx
  src/components/commons/loading-spinner.tsx
  src/components/features/home/home-popular-places.tsx
  src/constants/global.constant.ts
  src/constants/header.constants.ts
  src/constants/map.constants.ts
  src/constants/mypage.constants.ts
  src/lib/hooks/use-change-image-file.ts
  src/lib/hooks/use-plan-map.ts
  src/lib/hooks/use-schedule.ts
  src/lib/queries/use-bookmark-query.ts
  src/types/kakao-map.type.ts
Labels: refactor

#177 Refactor/#171 bookmark
  src/app/(mypage)/bookmarks/_components/bookmarks-list.tsx
  src/app/categories/[category]/category-client.tsx
  src/app/categories/[category]/page.tsx
  src/app/places/[id]/page.tsx
  src/app/plan-detail/_components/core/plan-header.tsx
  src/app/search/[category]/page.tsx
  src/app/search/_components/search-card.tsx
  src/app/search/page.tsx
  src/components/commons/bookmark-icon.tsx
  src/components/commons/category-filter-tabs.tsx
  src/components/commons/like-icon.tsx
  src/components/commons/loading-spinner.tsx
  src/components/features/card/place-card.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/features/card/search-card.tsx
  src/components/features/home/home-popular-places.tsx
  src/components/features/like/bookmark-button.tsx
  src/components/features/like/like-button.tsx
  src/components/layouts/search-bar.tsx
  src/lib/apis/bookmark/delete-bookmark.api.ts
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/apis/category/get-place.api.ts
  src/lib/apis/category/get-place.ts
  src/lib/apis/home/home.popular.api.ts
  src/lib/hooks/use-plan-filter.ts
  src/lib/hooks/use-popular-places.ts
  src/lib/hooks/use-search.ts
  src/lib/mutations/use-bookmark-mutation.ts
  src/lib/queries/use-get-places.ts
  src/middleware.ts
  src/types/card.type.ts
  src/types/category.type.ts
  src/types/home.popular-place.type.ts
  src/types/supabase.type.ts
  src/zustand/bookmark.store.ts
  src/zustand/home.place.store.ts
Labels: feat, refactor

#178 refactor: 메인페이지 컴포넌트 rcc/rsc 폴더 분리 (#176)
  src/app/_components/client/home-category-tap.tsx
  src/app/_components/client/home-main-carousel.tsx
  src/app/_components/client/home-popular-places.tsx
  src/app/_components/client/home-popular-schedules.tsx
  src/app/_components/client/home-weather-refresher.tsx
  src/app/_components/server/home-main-carousel-container.tsx
  src/app/_components/server/home-navigation-button.tsx
  src/app/_components/server/home-progress.tsx
  src/app/_components/server/home-weather-card.tsx
  src/app/_components/server/home-weather-container.tsx
  src/app/_components/server/home-weather-error.tsx
  src/app/_components/server/home-weather-header.tsx
  src/app/_components/server/home-weather-section.tsx
  src/app/categories/[category]/layout.tsx
  src/app/page.tsx
Labels: refactor

#179 Refactor/#171 bookmark
  src/app/(mypage)/bookmarks/_components/bookmarks-list.tsx
  src/app/(mypage)/bookmarks/page.tsx
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/mutations/use-bookmark-mutation.ts
  src/lib/queries/use-bookmark-query.ts
  src/lib/queries/use-get-bookmarks.ts
  src/lib/queries/use-get-data-count.ts
  src/types/category.type.ts
  src/types/mypage.type.ts
Labels: feat, refactor

#181 refactor: auth그륩 페이지 rcc/rsc 폴더 분리 (#180)
  src/app/(auth)/_components/client/auth-form.tsx
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/(auth)/_components/server/auth-footer.tsx
  src/app/(auth)/_components/server/auth-header.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/_components/client/auth-social-login.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(mypage)/account/_components/account-security-info.tsx
  src/components/features/error-message/error-message.tsx
  src/components/features/error-message/input-error-message.tsx
  src/components/features/input/password-input.tsx
  src/types/auth.type.ts
Labels: refactor

#183 Refactor/#164 plan detail optimization 1
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/core/plan-header.tsx
  src/app/plan-detail/_components/core/plan-map.tsx
  src/app/plan-detail/_components/core/plan-schedule.tsx
  src/app/plan-detail/_components/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/features/card/place-card.tsx
  src/app/plan-detail/_components/features/card/places-renderer.tsx
  src/app/plan-detail/_components/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/new/page.tsx
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-plan-detail-form.ts
  src/lib/hooks/use-plan-map.ts
  src/lib/hooks/use-schedule.ts
Labels: refactor

#184 Refactor/#182 auth semantic tag apply
  src/app/(auth)/_components/client/auth-form.tsx
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/(auth)/_components/server/auth-header.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/_components/client/auth-social-login.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/features/error-message/error-message.tsx
  src/components/features/error-message/input-error-message.tsx
  src/lib/hooks/use-drag-scroll.ts
Labels: refactor

#185 Refactor/#170 mypage pagination
  src/app/(mypage)/_components/mypage-sidebar.tsx
  src/app/(mypage)/bookmarks/[category]/page.tsx
  src/app/(mypage)/bookmarks/_components/bookmarks-list.tsx
  src/app/(mypage)/bookmarks/page.tsx
  src/app/(mypage)/likes/components/likes-list.tsx
  src/app/(mypage)/likes/page.tsx
  src/app/categories/[category]/category-client.tsx
  src/app/search/[category]/page.tsx
  src/components/commons/category-filter-tabs.tsx
  src/components/features/bookmark.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/ui/pagination.tsx
  src/lib/apis/bookmark/get-bookmark.api.ts
  src/lib/apis/category/get-place.api.ts
  src/lib/apis/like/count-like.api.ts
  src/lib/apis/like/get-like.api.ts
  src/lib/apis/search/get-place-by-categories.api.ts
  src/lib/hooks/use-bookmark.ts
  src/lib/queries/use-get-bookmarks.ts
  src/lib/queries/use-get-likes.ts
  src/middleware.ts
  src/types/mypage.type.ts
  src/types/supabase.type.ts
Labels: feat, refactor

#187 Refactor/#186 place image optimize
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/_components/client/home-popular-places.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/commons/loading-spinner.tsx
  src/components/commons/place-image.tsx
  src/constants/home.constants.ts
  src/types/common.type.ts
Labels: feat, refactor

#195 Refactor/#173 kpr refactor
  src/app/_components/client/home-category-tap.tsx
  src/app/categories/[category]/category-client.tsx
  src/app/places/[id]/_components/client/place-detail-content.tsx
  src/app/places/[id]/_components/client/place-location.tsx
  src/app/places/[id]/_components/plan-including-place.tsx
  src/app/places/[id]/_components/server/plan-including-place.tsx
  src/app/places/[id]/page.tsx
  src/app/plan-detail/_components/place-sidemenu.tsx
  src/app/search/[category]/page.tsx
  src/components/features/plan/README.md
  src/components/features/plan/place-modal-view.tsx
  src/components/features/plan/place-modal.tsx
  src/components/features/plan/plan-card-in-modal.tsx
  src/components/features/plan/plan-card-modal.tsx
  src/components/layouts/search-bar.tsx
  src/constants/tour.constants.ts
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/delete-bookmark.api.ts
Labels: refactor

#198 Feat/#192 qa test apply 1
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/core/plan-header.tsx
  src/app/plan-detail/_components/core/plan-map.tsx
  src/app/plan-detail/_components/core/plan-schedule.tsx
  src/app/plan-detail/_components/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/features/card/place-card.tsx
  src/app/plan-detail/_components/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/features/sidemenu/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/features/sidemenu/search-sidemenu.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/ui/textarea-with-count.tsx
  src/lib/hooks/use-plan-filter.ts
  src/lib/hooks/use-plan-map.ts
  src/types/kakao-map.type.ts
Labels: feat, bugfix, style

#199 Refactor/#173 kpr
  src/app/categories/[category]/category-client.tsx
  src/app/search/[category]/page.tsx
  src/components/commons/place-list-skeleton.tsx
  src/components/layouts/search-bar.tsx
  src/constants/tour.constants.ts
Labels: refactor

#197 Refactor/#194 auth query apply
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-in/_components/client/auth-social-login.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(mypage)/account/_components/account-profile-image.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-profile-modal.tsx
  src/app/_components/client/home-popular-schedules.tsx
  src/components/features/banner/jeju-banner.tsx
  src/components/features/like/bookmark-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/nav.tsx
  src/config/auth-provider.tsx
  src/config/tq-provider.tsx
  src/constants/mypage.constants.ts
  src/lib/apis/auth/auth-browser.api.ts
  src/lib/apis/auth/auth-server.api.ts
  src/lib/apis/profile/update-profile.api.ts
  src/lib/hooks/use-auth-check.ts
  src/lib/hooks/use-auth.ts
  src/lib/hooks/use-forgot-password.ts
  src/lib/hooks/use-popular-places.ts
  src/lib/hooks/use-reset-password.ts
  src/lib/hooks/use-social-login.ts
  src/lib/mutations/use-delete-profile-image-mutation.ts
  src/lib/mutations/use-update-nickname-mutation.ts
  src/lib/mutations/use-update-profile-image-mutation.ts
  src/lib/queries/auth-queries.ts
  src/types/auth.type.ts
  src/zustand/auth.store.ts
  src/zustand/forgot-password-store.ts
  src/zustand/reset-password-store.ts
Labels: feat, refactor

#201 Feat/#193 design qa
  public/character/sunglasses.png
  public/empty-result/empty_bookmarks.png
  public/empty-result/empty_comments.png
  public/empty-result/empty_likes.png
  public/empty-result/empty_plans.png
  public/empty-result/empty_result.png
  public/emptyresult/empty_result.svg
  public/notfound/Frame 1707483139.svg
  public/notfound/Frame 1707483139@2x.svg
  public/notfound/not_found.png
  src/app/(mypage)/account/_components/account-profile-image-button.tsx
  src/app/(mypage)/account/_components/account-profile-image.tsx
  src/app/(mypage)/bookmarks/_components/bookmarks-list.tsx
  src/app/(mypage)/comments/_components/comments-list.tsx
  src/app/(mypage)/likes/components/likes-list.tsx
  src/app/(mypage)/reservations/page.tsx
  src/app/_components/server/home-weather-header.tsx
  src/app/air-ticket/_components/ticket-list.tsx
  src/app/my-plan/_components/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/app/not-found.tsx
  src/app/places/[id]/_components/client/place-detail-content.tsx
  src/app/search/[category]/page.tsx
  src/app/search/_components/empty-result.tsx
  src/components/commons/category-filter-tabs.tsx
  src/components/commons/empty-result-link.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/icons/add-icon.tsx
  src/components/icons/arrow-icon.tsx
  src/components/icons/close-icon.tsx
  src/components/icons/edit-icon.tsx
  src/components/icons/location-icon.tsx
  src/components/icons/phone-icon.tsx
  src/components/icons/time-icon.tsx
  src/components/layouts/search-bar.tsx
  src/components/ui/dynamic-pagination.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  src/middleware.ts
Labels: style, refactor

#202 Refactor/#164 plan detail optimization 3
  package.json
  pnpm-lock.yaml
  src/app/my-plan/_components/client/plan-filter-input.tsx
  src/app/my-plan/_components/client/plan-filter-menu.tsx
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/my-plan/_components/server/filter-button.tsx
  src/app/my-plan/page.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-map.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/app/plan-detail/_components/client/features/comment/comment-input.tsx
  src/app/plan-detail/_components/client/features/comment/comment.tsx
  src/app/plan-detail/_components/client/features/modal/day-select-required-modal.tsx
  src/app/plan-detail/_components/client/features/modal/schedule-created-modal.tsx
  src/app/plan-detail/_components/client/features/modal/schedule-delete-modal.tsx
  src/app/plan-detail/_components/client/features/modal/schedule-save-modal.tsx
  src/app/plan-detail/_components/client/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/app/plan-detail/_components/core/plan-header.tsx
  src/app/plan-detail/_components/core/plan-map.tsx
  src/app/plan-detail/_components/core/plan-schedule.tsx
  src/app/plan-detail/_components/place-sidemenu.tsx
  src/app/plan-detail/_components/plan-form.tsx
  src/app/plan-detail/_components/server/comments-section.tsx
  src/app/plan-detail/_components/server/not-found.tsx
  src/app/plan-detail/_components/server/places-renderer.tsx
  src/app/plan-detail/new/page.tsx
  src/lib/apis/comments/get-comments.api.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-plan-map.ts
  src/lib/hooks/use-schedule.ts
  src/types/comment.type.ts
  src/types/plan.type.ts
  src/types/supabase.type.ts
  src/zustand/plan.store.ts
Labels: bugfix, refactor

#203 Style/#40 air ticket 디자인 시안 반영
  public/banner-images/airplane_footer.png
  public/emptyresult/ticket_empty_result.png
  public/icons/plane.svg
  public/icons/plane_departure.svg
  public/icons/plane_land.svg
  src/app/air-ticket/_components/date-options.tsx
  src/app/air-ticket/_components/ticket-card.tsx
  src/app/air-ticket/_components/ticket-list.tsx
  src/app/air-ticket/_components/ticket-search-form.tsx
  src/app/air-ticket/_components/ticket-search-selector.tsx
  src/app/air-ticket/_utils/ticket-uitls.ts
  src/app/air-ticket/page.tsx
  src/components/commons/combo-box.tsx
  src/types/air-ticket-type.ts
Labels: style

#206 Feat/#205 plan comments
  src/app/(mypage)/comments/page.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/comment/comment-input.tsx
  src/app/plan-detail/_components/client/features/comment/comment.tsx
  src/app/plan-detail/_components/client/features/comment/comments-section.tsx
  src/app/plan-detail/_components/server/comments-section.tsx
  src/lib/apis/comments/client-comments.api.ts
  src/lib/apis/comments/server-comments.api.ts
  src/lib/mutations/use-comment-mutation.ts
  src/lib/queries/use-get-comments.ts
  src/types/plan-detail.type.ts
Labels: feat

#207 Style/#200 design qa fix
  src/app/(auth)/_components/client/auth-form.tsx
  src/app/(auth)/_components/server/auth-footer.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/sign-in/_components/client/auth-social-login.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/_components/client/home-category-tap.tsx
  src/app/_components/client/home-popular-places.tsx
  src/app/_components/server/home-weather-card.tsx
  src/app/_components/server/home-weather-header.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/components/features/banner/jeju-banner.tsx
  src/components/layouts/footer.tsx
  src/components/layouts/header.tsx
  src/constants/auth.constants.ts
  src/lib/apis/auth/auth-server.api.ts
  src/lib/apis/home/home.popular.api.ts
  src/lib/hooks/use-auth-check.ts
  src/lib/queries/auth-queries.ts
  src/lib/utils/auth-error.util.ts
  src/middleware.ts
  src/types/auth.type.ts
Labels: feat, style, refactor

#208 Feat/#193 design qa
  src/app/(mypage)/account/_components/account-profile-image.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-profile-modal.tsx
  src/app/(mypage)/account/page.tsx
  src/app/(mypage)/bookmarks/[category]/page.tsx
  src/app/(mypage)/comments/page.tsx
  src/app/(mypage)/likes/page.tsx
  src/app/(mypage)/reservations/page.tsx
  src/app/categories/[category]/page.tsx
  src/app/community/_components/community-plan-list.tsx
  src/app/community/page.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/ui/dynamic-pagination.tsx
  src/components/ui/toaster.tsx
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/delete-bookmark.api.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/apis/profile/update-profile.api.ts
  src/lib/hooks/use-custom-toast.ts
  src/lib/hooks/use-schedule.ts
  src/lib/hooks/use-toast.ts
  src/lib/mutations/use-delete-plan-mutation.ts
  src/lib/mutations/use-update-profile-image-mutation.ts
  src/types/mypage.type.ts
Labels: feat, bugfix

#211 Feat/#193 design qa
  src/app/(mypage)/_components/_client/mypage-data-counts.tsx
  src/app/(mypage)/_components/_client/mypage-pagination.tsx
  src/app/(mypage)/_components/_client/mypage-sidebar.tsx
  src/app/(mypage)/account/_components/_client/account-personal-info.tsx
  src/app/(mypage)/account/_components/_client/account-profile-image-button.tsx
  src/app/(mypage)/account/_components/_client/account-profile-image.tsx
  src/app/(mypage)/account/_components/_client/account-profile-info.tsx
  src/app/(mypage)/account/_components/_client/account-profile-modal.tsx
  src/app/(mypage)/account/_components/_client/account-security-info.tsx
  src/app/(mypage)/account/_components/account-personal-info.tsx
  src/app/(mypage)/account/_components/account-profile-info.tsx
  src/app/(mypage)/account/_components/account-security-info.tsx
  src/app/(mypage)/account/page.tsx
  src/app/(mypage)/bookmarks/[category]/page.tsx
  src/app/(mypage)/bookmarks/_components/_client/bookmarks-list.tsx
  src/app/(mypage)/comments/_components/_client/comments-list.tsx
  src/app/(mypage)/comments/_components/_client/my-comment.tsx
  src/app/(mypage)/comments/page.tsx
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/likes/components/_client/likes-list.tsx
  src/app/(mypage)/likes/page.tsx
  src/app/categories/[category]/page.tsx
  src/app/categories/_components/_client/category-client.tsx
  src/app/community/_components/_client/community-plan-list.tsx
  src/app/community/_components/_client/community-sort-dropdown.tsx
  src/app/community/page.tsx
  src/app/plan-detail/_components/client/features/comment/comment-input.tsx
  src/lib/apis/comments/client-comments.api.ts
  src/lib/mutations/use-comment-mutation.ts
  src/middleware.ts
Labels: bugfix

#212 feat: 검색바에 로딩 스피너 추가 및 코드 정리 (#173)
  src/components/layouts/header.tsx
  src/components/layouts/search-bar.tsx
Labels: feat, refactor

#214 Refactor/#173 place modal 일정 생성 페이지 모달창
  public/logo/color_logo_single_bg.png
  src/app/layout.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-map.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/components/features/plan/place-modal-view.tsx
  src/components/features/plan/place-modal.tsx
  src/lib/apis/plan/plan.api.ts
  src/lib/mutations/use-like-mutation.ts
  src/lib/queries/use-get-place-basic-info.ts
  src/lib/queries/use-get-place-detail-info.ts
  src/lib/queries/use-get-plans.ts
  src/types/place-modal.type.ts
Labels: feat

#215 refactor: 인증 폼 및 검색바 컴포넌트 개선 (#200)
  src/app/(auth)/_components/client/auth-form.tsx
  src/components/layouts/search-bar.tsx
Labels: feat, refactor

#216 Feat/#213 category region tabs
  src/app/categories/_components/_client/category-client.tsx
  src/app/categories/_components/_client/category-region-tabs.tsx
  src/app/search/[category]/page.tsx
  src/components/commons/place-list-skeleton.tsx
  src/lib/apis/category/get-place.api.ts
  src/lib/queries/use-get-places.ts
  src/types/category.type.ts
Labels: feat

#219 Feat/#193 design qa
  src/app/community/_components/_client/community-sort-dropdown.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/lib/apis/plan/plan.api.ts
Labels: bugfix

#217 Feat/#40 air ticket
  package.json
  pnpm-lock.yaml
  src/app/air-ticket/_components/date-options.tsx
  src/app/air-ticket/_components/ticket-card.tsx
  src/app/air-ticket/_components/ticket-list.tsx
  src/app/air-ticket/_components/ticket-search-form.tsx
  src/app/air-ticket/_components/ticket-search-selector.tsx
  src/app/air-ticket/_utils/ticket-uitls.ts
  src/app/air-ticket/page.tsx
  src/app/api/flight/route.js
  src/types/air-ticket-type.ts
Labels: feat, style, refactor

#218 Bugfix/plan save bug pr
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/app/plan-detail/_components/server/places-renderer.tsx
  src/app/plan-detail/new/page.tsx
  src/components/commons/edit-and-delete-dropdown.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/constants/mypage.constants.ts
  src/constants/plan.constants.ts
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-plan-map.ts
  src/lib/hooks/use-schedule.ts
  src/lib/mutations/use-update-plan-mutation.ts
  src/lib/queries/use-get-filtered-plans.ts
  src/types/common.type.ts
  src/types/plan.type.ts
  src/zustand/plan.store.ts
Labels: bugfix

#220 Feat/#193 design qa
  src/app/(mypage)/bookmarks/_components/_client/bookmarks-list.tsx
  src/app/(mypage)/comments/_components/_client/comments-list.tsx
  src/app/(mypage)/comments/_components/_client/my-comment.tsx
  src/app/(mypage)/comments/page.tsx
  src/app/(mypage)/likes/components/_client/likes-list.tsx
  src/app/(mypage)/likes/page.tsx
  src/app/categories/[category]/page.tsx
  src/app/categories/_components/_client/category-client.tsx
  src/app/categories/_components/_client/category-region-tabs.tsx
  src/app/community/_components/_client/community-plan-list.tsx
  src/app/community/_components/_client/community-sort-dropdown.tsx
  src/app/plan-detail/_components/client/features/comment/comments-section.tsx
  src/components/features/card/place-card.tsx
  src/components/features/like/bookmark-button.tsx
  src/components/icons/arrow-icon.tsx
  src/lib/apis/plan/plan.api.ts
Labels: refactor

#221 Bugfix/#210 minor plan bug pr
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/lib/hooks/use-schedule.ts
  src/lib/utils/get-default-plan-image.ts
Labels: bugfix

#222 style: 전역 레이아웃 스타일 개선
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/components/layouts/footer.tsx
Labels: style, refactor

#223 Feat/#192 plan metadata sementictag
  src/app/my-plan/_components/client/plan-filter-input.tsx
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/features/modal/schedule-created-modal.tsx
  src/app/plan-detail/new/page.tsx
  src/constants/plan.constants.ts
  src/lib/utils/get-default-plan-image.ts
Labels: feat

#225 Refactor/#173 design qa 메타데이터 및 장소상세페이지 이미지 왼쪽정렬 반영
  src/app/places/[id]/_components/client/place-detail-content.tsx
  src/app/places/[id]/_components/client/place-location.tsx
  src/app/places/[id]/page.tsx
  src/app/search/[category]/layout.tsx
  src/components/layouts/nav.tsx
Labels: refactor

#227 Hotfix/210 plan dropdown issue
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/components/commons/edit-and-delete-dropdown.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-schedule.ts
Labels: bugfix

#228 Refactor/#173 constants 상수화는 못하고 로직 수정
  src/app/places/[id]/_components/server/plan-including-place.tsx
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/delete-bookmark.api.ts
Labels: feat

#229 Feat/#189 reservations page
  next.config.mjs
  public/empty-result/ticket_empty_result.png
  src/app/(mypage)/comments/page.tsx
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/reservations/_components/_server/reservations-card-arrow.tsx
  src/app/(mypage)/reservations/_components/_server/reservations-card.tsx
  src/app/(mypage)/reservations/_components/_server/reservations-flight-info.tsx
  src/app/(mypage)/reservations/page.tsx
  src/app/air-ticket/_components/date-options.tsx
  src/app/air-ticket/_components/ticket-card.tsx
  src/app/air-ticket/_components/ticket-list.tsx
  src/app/air-ticket/_components/ticket-search-form.tsx
  src/app/air-ticket/_components/ticket-search-selector.tsx
  src/app/air-ticket/_utils/ticket-uitls.ts
  src/app/air-ticket/page.tsx
  src/components/icons/arrow-icon.tsx
  src/components/icons/flight-icon.tsx
  src/lib/apis/flight/get-reservations.api.ts
  src/lib/utils/date.ts
  src/middleware.ts
  src/types/air-ticket.type.ts
  src/types/mypage.type.ts
  src/types/supabase.type.ts
Labels: feat, style

#230 Style/#40 air ticket 변경된 디자인 적용
  src/app/(mypage)/likes/components/_client/likes-list.tsx
  src/app/air-ticket/_components/ticket-search-form.tsx
  src/app/air-ticket/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/middleware.ts
Labels: style

#233 fix: 북마크 버튼 일단 주석 (#173)
  src/app/places/[id]/_components/client/place-detail-content.tsx
  src/lib/apis/bookmark/add-bookmark.api.ts
  src/lib/apis/bookmark/delete-bookmark.api.ts
Labels: hotfix

#235 Bugfix/#210 minor error about plan server rendering
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/modal/schedule-created-modal.tsx
  src/app/plan-detail/new/page.tsx
  src/data/carousel-data.json
  src/lib/hooks/use-schedule.ts
  src/lib/queries/use-bookmark-query.ts
Labels: hotfix

#238 Feat/easter egg add
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/commons/ConsoleEasterEgg.tsx
  src/components/commons/EasterEggManager.tsx
  src/components/commons/EasterEggWrapper.tsx
  src/components/commons/KonamiEasterEgg.tsx
Labels: feat

#240 feat: 이미지 파일명 관련 업로드 이슈 해결 (#210)
  src/app/community/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-schedule.ts
Labels: bugfix

#242 Feat/#40 air ticket
  src/app/air-ticket/_components/ticket-list.tsx
  src/app/air-ticket/_utils/ticket-uitls.ts
  src/app/air-ticket/page.tsx
Labels: feat

#245 Fix/#244 qa feedback 1
  src/app/(mypage)/account/_components/_client/account-personal-info.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/app/plan-detail/_components/server/places-renderer.tsx
  src/lib/apis/auth/auth-server.api.ts
  src/lib/apis/map/directions.ts
  src/lib/hooks/use-schedule.ts
  src/lib/utils/get-default-plan-image.ts
  src/lib/utils/plan.util.ts
  src/types/plan.type.ts
  src/types/user.type.ts
  src/zustand/plan.store.ts
Labels: bugfix

#246 main 브랜치에 dev 브랜치 작업 병합
  src/app/(mypage)/account/_components/_client/account-personal-info.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/app/plan-detail/_components/server/places-renderer.tsx
  src/lib/apis/auth/auth-server.api.ts
  src/lib/apis/map/directions.ts
  src/lib/hooks/use-schedule.ts
  src/lib/utils/get-default-plan-image.ts
  src/lib/utils/plan.util.ts
  src/types/plan.type.ts
  src/types/user.type.ts
  src/zustand/plan.store.ts
Labels: bugfix

#247 Style/#226 design qa 1
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-map.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/core/plan-sidemenu.tsx
  src/app/plan-detail/_components/client/features/button/plan-save-button.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/app/plan-detail/_components/client/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-searchbar.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/app/plan-detail/new/_components/.gitkeep
  src/app/plan-detail/new/page.tsx
  src/components/commons/category-filter-tabs.tsx
  src/components/commons/character-modal.tsx
  src/components/features/map/clusterer.tsx
  src/components/features/map/marker.tsx
  src/components/layouts/nav.tsx
  src/components/ui/dynamic-pagination.tsx
  src/components/ui/pagination.tsx
  src/constants/map.constants.ts
  src/lib/hooks/use-plan-map.ts
  src/lib/hooks/use-schedule.ts
  src/lib/hooks/use-sidemenu.ts
Labels: style

#248 Style/#226 design qa 2
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-map.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/core/plan-sidemenu.tsx
  src/app/plan-detail/_components/client/features/button/plan-save-button.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/components/commons/character-modal.tsx
  src/components/features/plan/place-modal-view.tsx
  src/components/features/plan/place-modal.tsx
  src/components/ui/dialog.tsx
Labels: style

#250 Style/#249 responsive design
  src/app/(mypage)/_components/_client/mypage-sidebar.tsx
  src/app/(mypage)/_components/_client/mypage-top-nav.tsx
  src/app/(mypage)/account/_components/_client/account-personal-info.tsx
  src/app/(mypage)/account/_components/_client/account-profile-info.tsx
  src/app/(mypage)/account/_components/_client/account-security-info.tsx
  src/app/(mypage)/account/page.tsx
  src/app/(mypage)/layout.tsx
  src/app/layout.tsx
  src/components/features/nav-mypage/mypage-button.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/icons/calendar-icon.tsx
  src/components/icons/community-icon.tsx
  src/components/icons/home-icon.tsx
  src/components/icons/mypage-icon.tsx
  src/components/layouts/bottom-nav.tsx
  src/config/tq-provider.tsx
  src/constants/mypage.constants.ts
  src/types/mypage.type.ts
  tailwind.config.ts
Labels: feat, style

#255 Feat/#189 reservations page
  public/empty-result/empty_reservations.png
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/reservations/page.tsx
  src/lib/apis/flight/get-reservations.api.ts
Labels: feat

#251 Style/#249 responsive design
  src/app/(mypage)/_components/_client/mypage-activities-dropdown.tsx
  src/app/(mypage)/_components/_client/mypage-data-counts.tsx
  src/app/(mypage)/_components/_client/mypage-top-nav.tsx
  src/app/(mypage)/account/_components/_client/account-personal-info.tsx
  src/app/(mypage)/account/_components/_client/account-profile-image.tsx
  src/app/(mypage)/account/_components/_client/account-profile-info.tsx
  src/app/(mypage)/account/_components/_client/account-security-info.tsx
  src/app/(mypage)/bookmarks/[category]/page.tsx
  src/app/(mypage)/bookmarks/_components/_client/bookmarks-list.tsx
  src/app/(mypage)/comments/_components/_client/comments-list.tsx
  src/app/(mypage)/comments/_components/_client/my-comment.tsx
  src/app/(mypage)/comments/page.tsx
  src/app/(mypage)/likes/components/_client/likes-list.tsx
  src/app/(mypage)/likes/page.tsx
  src/app/(mypage)/reservations/_components/_server/reservations-card-arrow.tsx
  src/app/(mypage)/reservations/_components/_server/reservations-card.tsx
  src/app/(mypage)/reservations/_components/_server/reservations-flight-info.tsx
  src/app/(mypage)/reservations/page.tsx
  src/app/layout.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/icons/arrow-icon.tsx
  src/components/layouts/bottom-nav.tsx
  src/components/ui/dropdown-menu.tsx
  src/config/tq-provider.tsx
  src/types/common.type.ts
  src/types/plan.type.ts
Labels: style

#261 Style/#249 responsive design
  public/banner-images/plan_banner_mini.png
  src/app/_components/client/home-category-tap.tsx
  src/app/_components/client/home-popular-schedules.tsx
  src/app/_components/server/home-weather-card.tsx
  src/app/_components/server/home-weather-container.tsx
  src/app/_components/server/home-weather-header.tsx
  src/app/_components/server/home-weather-section.tsx
  src/app/categories/_components/_client/category-client.tsx
  src/app/community/_components/_client/community-plan-list.tsx
  src/app/community/_components/_client/community-sort-dropdown.tsx
  src/app/community/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/search/_components/banner.tsx
  src/components/commons/like-button.tsx
  src/components/commons/like-icon.tsx
  src/components/features/banner/jeju-banner.tsx
  src/components/features/card/plan-horizontal_card.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/features/like/bookmark-button.tsx
  src/components/features/like/like-button.tsx
  src/components/icons/bookmark-icon.tsx
  src/components/icons/like-icon.tsx
  src/components/icons/search-icon.tsx
  src/components/layouts/footer.tsx
  src/components/layouts/header.tsx
  src/components/layouts/nav.tsx
  src/components/layouts/search-bar.tsx
  tailwind.config.ts
Labels: style

#257 Style/#253 auth page responsive
  public/icons/arrow_full_left.svg
  src/app/(auth)/_components/client/auth-form.tsx
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/(auth)/_components/server/auth-footer.tsx
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/layout.tsx
  src/components/layouts/header.tsx
  src/constants/auth.constants.ts
  src/lib/schemas/auth-schema.ts
Labels: feat, style, refactor

#263 Style/#259 main page responsive
  public/banner-images/mobile-jeju-banner.jpg
  src/app/(mypage)/bookmarks/_components/_client/bookmarks-list.tsx
  src/app/_components/client/home-popular-places.tsx
  src/app/_components/client/home-popular-schedules.tsx
  src/app/_components/server/home-progress.tsx
  src/app/categories/_components/_client/category-client.tsx
  src/app/page.tsx
  src/app/search/[category]/page.tsx
  src/components/commons/duration.tsx
  src/components/features/banner/jeju-banner.tsx
  src/components/features/card/place-card.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/features/like/bookmark-button.tsx
  src/components/layouts/footer.tsx
  src/types/card.type.ts
Labels: feat, style, refactor

#264 Style/#252 responsive plandetail
   -i
  package.json
  pnpm-lock.yaml
  public/icons/mdi_filter_mobile.svg
  src/app/my-plan/_components/client/filter-button.tsx
  src/app/my-plan/_components/client/filter-tag.tsx
  src/app/my-plan/_components/client/plan-filter-input.tsx
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/features/button/plan-save-button.tsx
  src/app/plan-detail/new/page.tsx
  src/components/commons/duration.tsx
  src/components/commons/empty-result-link.tsx
  src/components/commons/like-button.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/ui/textarea-with-count.tsx
  src/lib/apis/plan/plan.api.ts
  src/lib/hooks/use-schedule.ts
  src/lib/utils/date.ts
  src/types/common.type.ts
Labels: style

#266 style: 인증 페이지 레이아웃 및 전역 스타일 개선
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/_components/client/home-main-carousel.tsx
  src/app/_components/server/home-navigation-button.tsx
  src/app/_components/server/home-progress.tsx
  src/app/community/_components/_client/community-plan-list.tsx
  src/app/community/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/commons/KonamiEasterEgg.tsx
  src/components/features/error-message/input-error-message.tsx
  src/components/layouts/footer.tsx
Labels: style, refactor

#267 Style/#249 responsive design
  src/app/(mypage)/_components/_client/mypage-header.tsx
  src/app/(mypage)/layout.tsx
  src/app/_components/client/home-category-tap.tsx
  src/app/_components/server/home-weather-card.tsx
  src/app/_components/server/home-weather-container.tsx
  src/app/_components/server/home-weather-section.tsx
  src/app/categories/[category]/page.tsx
  src/app/categories/_components/_client/category-client.tsx
  src/app/categories/_components/_client/category-region-tabs.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/search/_components/banner.tsx
  src/components/features/card/place-card.tsx
  src/components/layouts/footer.tsx
  src/components/layouts/header.tsx
  src/components/layouts/search-bar.tsx
  src/components/ui/input.tsx
  src/config/tq-provider.tsx
  tailwind.config.ts
Labels: style

#270 Style/#252 responsive design
  src/app/places/[id]/_components/client/place-detail-content.tsx
  src/app/plan-detail/[planId]/page.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-map.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/core/plan-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/app/plan-detail/new/page.tsx
  src/components/commons/category-badge.tsx
  src/components/features/map/clusterer.tsx
  src/components/features/map/marker.tsx
  src/components/ui/textarea-with-count.tsx
  src/components/ui/textarea.tsx
  src/constants/map.constants.ts
  src/lib/utils/date.ts
  tailwind.config.ts
Labels: style

#269 Feature/#268 design qa responsive apply
  public/banner-images/mobile-banner1.jpg
  public/banner-images/mobile-banner2.jpg
  public/banner-images/mobile-banner3.jpg
  public/banner-images/mobile-banner4.jpg
  public/weather/rain.svg
  src/app/(auth)/_components/client/auth-layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/_components/client/carousel-skeleton.tsx
  src/app/_components/client/home-main-carousel.tsx
  src/app/_components/client/home-popular-places.tsx
  src/app/_components/client/home-popular-schedules.tsx
  src/app/_components/server/home-main-carousel-container.tsx
  src/app/_components/server/home-weather-container.tsx
  src/app/_components/server/home-weather-error.tsx
  src/app/_components/server/home-weather-header.tsx
  src/app/_components/server/home-weather-section.tsx
  src/components/layouts/bottom-nav.tsx
  src/components/layouts/header.tsx
  src/data/carousel-data.json
  src/lib/apis/home/home.api.ts
  src/lib/utils/home.weather.util.ts
  src/types/home.carousel.type.ts
  src/types/home.weather.type.ts
Labels: feat, style, refactor

#271 Refactor/#254 responsive tab 카테고리탭 (소흔님) 장소 상세 반응형 완료
  src/app/_components/client/home-category-tap.tsx
  src/app/places/[id]/_components/client/place-detail-content.tsx
  src/app/places/[id]/_components/client/places-header.tsx
  src/app/places/[id]/_components/server/plan-including-place.tsx
  src/app/places/[id]/page.tsx
  src/components/commons/category-badge.tsx
  src/types/category.type.ts
Labels: style

#274 Style/#252 responsive design bottomsheet
  next.config.mjs
  src/app/(mypage)/account/_components/_client/account-profile-modal.tsx
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/card/place-card-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/bookmark-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-searchbar.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/app/plan-detail/_components/client/plan-form.tsx
  src/components/commons/place-image.tsx
  src/components/commons/plan-image.tsx
  src/components/commons/reset-password-success-modal.tsx
  src/components/features/plan/place-modal.tsx
  src/components/ui/sheet.tsx
Labels: style

#278 Style/#252 responsive design card
  src/app/my-plan/_components/client/plan-filter-section.tsx
  src/app/my-plan/page.tsx
  src/components/features/card/plan-vertical-card.tsx
  src/components/layouts/nav.tsx
  src/lib/apis/plan/plan.api.ts
  src/middleware.ts
  src/types/plan.type.ts
Labels: style
