Repository RE6CT/jeju-olleyo, pull requests merged in 2025-05, with the labels that each got.

#286 fix: 검색시 발생하는 layoutshift 현상 해결 (#281)
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
Labels: bugfix

#288 Bugfix/#281 search layout shift
  src/app/plan-detail/_components/client/core/plan-schedule.tsx
  src/app/plan-detail/_components/client/features/sidemenu/place-sidemenu-layout.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/components/commons/alert-modal.tsx
  src/components/features/nav-mypage/mypage-modal.tsx
  src/components/layouts/bottom-nav.tsx
  src/lib/queries/auth-queries.ts
Labels: bugfix

#290 Feature/#268 design qa responsive apply
  src/components/layouts/footer.tsx
  src/lib/queries/auth-queries.ts
Labels: style

#292 fix: 날짜 선택 및 항공권 검색 폼 레이아웃 개선
  src/app/air-ticket/_components/date-options.tsx
  src/app/air-ticket/_components/ticket-search-form.tsx
  src/app/air-ticket/page.tsx
Labels: hotfix

#295 Bugfix/#281 search layout sticky
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/app/plan-detail/_components/client/core/plan-sidemenu.tsx
  src/app/plan-detail/_components/client/features/card/place-card.tsx
  src/app/plan-detail/_components/client/features/sidemenu/search-sidemenu.tsx
  src/components/commons/plan-image.tsx
Labels: bugfix

#294 fix : 오류 해결 (#40)
  src/app/air-ticket/_components/date-options.tsx
  src/app/air-ticket/page.tsx
Labels: bugfix

#297 fix: 검색어 글자수 제한 추가 (#193)
  src/components/layouts/search-bar.tsx
Labels: feat

#298 fix: planId가 없는 새 일정 이미지도 image bucket에 저장되도록 수정 (#281)
  src/app/plan-detail/_components/client/core/plan-header.tsx
  src/lib/apis/plan/plan.api.ts
Labels: bugfix
